---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    # role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: pg_back
    image: ${MOLECULE_PLATFORM_IMAGE:-"geerlingguy/docker-centos8-ansible"}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
